### ISSUE TITLE
Proptypes not defined

### ISSUE THREAD

**Issue by mmarovich** [schowdhuri/react-daytime#1]
Hey!  I'd really like to use your library here, but things are a little outdated.  When I use it it throws an error that propTypes are undefined, which makes sense because as of react version 15 something they separated it in the code, so you have to import propTypes from their 'prop-types' lib.

When I did that, I got another error saying 
```
417:48-60 "export 'default' (imported as 'ReactDaytime') was not found in 'react-daytime'
```
I don't know what's causing this.  You know your code better than me.  Let me know if you know what's up, so I can use your awesome calendar! : )

**Comment by schowdhuri** [comment]
An update had been long overdue! I bumped all the way to React 16. Didn't face the problem you mention. Can you upgrade to v1.2.1 and check if the error goes away?

**Comment by mmarovich** [comment]
Thank you so much!  I'll test it out over the weekend and let you know how it goes.  : )

**Comment by mmarovich** [comment]
Guess what?  It works.  Feel free to close out this issue.  : )))  Thanks for creating an awesome component.

**Comment by schowdhuri** [comment]
You're welcome! Glad you like it :)
